config/routes.rb
GistTools::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root 'pages#index'
  get "pages/index"
  get "gists/:id" => "gists#show", as: "gist"
  get "gists" => "gists#index", as: "gists"
  post "gists" => "gists#display_gist"
end

app/models/gist.rb
class Gist

  def initialize(id, access_token)
    @id = id
    @github_access_token = access_token
  end

  def raw_data
    if @github_access_token
      url = "https://api.github.com/gists/#{@id}?access_token=#{@github_access_token}"
    else
      url = "https://api.github.com/gists/#{@id}"
    end
    JSON.parse(open(url).read)
  end

  def comments
    raw_data["comments"]
  end

  def forks
    raw_data["forks"].count
  end

  def revisions
    raw_data["history"].count
  end

  def age
    ((Time.now - Time.parse(raw_data["created_at"])) / 60 / 60).round
  end

  def commits
    if @github_access_token
      JSON.parse(open(raw_data["commits_url"]+"?access_token=#{@github_access_token}").read).count
    else
      JSON.parse(open(raw_data["commits_url"]).read).count
    end
  end

  def characters
    raw_data["files"].each_value{|v| return v["size"]}
  end

  def file_name
    raw_data["files"].each_value{|v| return v["filename"]}
  end

  def file_body
    raw_data["files"].each_value{|v| return open(v["raw_url"]).readlines}
  end

  def url
    raw_data["html_url"]
  end

  def description
    raw_data["description"].to_s
  end

end

app/models/user.rb
require "active_record_helpers.rb"

class User < ActiveRecord::Base
  require 'open-uri'
  require 'json'
  include Authentication::ActiveRecordHelpers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  def raw_gists
    url = "https://api.github.com/users/#{self.github_username}/gists?access_token=#{self.github_access_token}"
    @result = JSON.parse(open(url).read)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :rate_limit, :rate_limit_reset

  def rate_limit
    if user_signed_in?
      url = "https://api.github.com/rate_limit?access_token=#{current_user.github_access_token}"
    else
      url = "https://api.github.com/rate_limit"
    end
    @rate_limit = JSON.parse(open(url).read)["resources"]["core"]
    @rate_limit["remaining"]
  end

  def rate_limit_reset
    Time.at(@rate_limit["reset"]).localtime.strftime("%l:%M%P")
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController

  def index
    @gists = current_user.raw_gists
  end

  def show
    if user_signed_in?
      @gist = Gist.new(params[:id], current_user.github_access_token)
    else
      @gist = Gist.new(params[:id], nil)
    end
  end

  def display_gist
    redirect_to gist_path(params[:id])
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    user = User.find_for_oauth(request.env["omniauth.auth"])
    if user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Github"
      sign_in_and_redirect user, :event => :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/active_record_helpers.rb
module Authentication
  module ActiveRecordHelpers

    def self.included(base)
      base.extend ClassMethods
    end

    module ClassMethods
      def find_for_oauth(auth)
        record = where(provider: auth.provider, uid: auth.uid.to_s).first
        record || create(provider: auth.provider, uid: auth.uid, email: auth.info.email, password: Devise.friendly_token[0,20], name: auth.info.name, github_username: auth.info.nickname, github_access_token: auth.credentials.token)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/gists/index.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3 opaque_bg">
    <h1 class="large">Your <span class="neon_green">Gists</span></h1>
    <% @gists.each do |gist| %>
      <p class="line" id="gist_index">
        <%= link_to "", gist["html_url"], class: "genericon genericon-github" %>
        <a href="<%= gist_path(gist["id"]) %>">
        <%= Time.parse(gist["updated_at"]).strftime("%b %e, %Y") %><br>
        <span class="stat_text"><%= gist["description"] %></span>
        </a>
      </p>
    <% end %>
  </div>
</div>

app/views/gists/show.html.erb
<div class="row" id="gist_show">
  <div class="col-sm-6 col-sm-offset-3 opaque_bg">
    <%= link_to "", @gist.url, class: "genericon genericon-github", id: "source_icon_link" %>
    <h1 class="large light_text"><span class="neon_green">Gist</span><%= params[:id] %></h1>
    <h1 class="large light_text"><%= @gist.file_name %></h1>
    <div class="row line">
      <p class="col-sm-4"><span class="stat_num"><%= @gist.comments %></span><br><span class="stat_text">Comments</span></p>
      <p class="col-sm-4 col-sm-offset-2"><span class="stat_num"><%= @gist.forks %></span><br><span class="stat_text">Forks</span></p>
    </div>

    <div class="row line">
      <p class="col-sm-4"><span class="stat_num"><%= @gist.revisions %></span><br><span class="stat_text">Revisions</span></p>
      <p class="col-sm-4 col-sm-offset-2"><span class="stat_num"><%= @gist.age %></span><br><span class="stat_text">hours old</span></p>
    </div>

    <div class="row line">
      <p class="col-sm-4"><span class="stat_num"><%= @gist.commits %></span><br><span class="stat_text">Commits</span></p>
      <p class="col-sm-4 col-sm-offset-2"><span class="stat_num"><%= @gist.characters %></span><br><span class="stat_text">Characters</span></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GistTools</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    "genericons", media: "all", "data-turbolinks-track" => true %>
</head>
<body>
  <div id="api_counter"><%= rate_limit %> Github API hits left until <%= rate_limit_reset %></div>
  <a href "<%= root_url %>"><h1 id="site_title"><span class="neon_green">Gist</span><span class="light_text">tools</span></h1></a>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <span>
  <% if current_user %>
    <%= button_to "Your Gists", gists_path, class: "circle_link" %><br>
    <%= link_to "", destroy_user_session_path, method: :delete, class: "genericon genericon-github big_icon orange_icon", id: "sign_out" %>
    <span class="icon_text">Sign out</span>
  <% else %>
    <%= link_to "", "users/auth/github", class: "genericon genericon-github big_icon", id: "sign_in" %>
    <span class="icon_text">Sign in with Github</span>
  <% end %>
  </span>
  <div class="left_triangle"></div>
  <%= yield %>
</body>
</html>

<script>
  $( "#sign_in, #sign_out" ).hover(
    function() {
      $( ".icon_text" ).css( "color", "white" );
    }, function() {
      $( ".icon_text" ).css( "color", "transparent" );
    }
  );

  if(<%= rate_limit %> <= 40)
    $("#api_counter").css("color", "orangered");

</script>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3 opaque_bg">
    <h1 class="large light_text">Stats about your <span class="neon_green">Gists</span></h1>
    <h1>
      <%= link_to "Sign in with Github", "users/auth/github" %>
      <br>or<br>
      Enter a <span class="neon_green">Gist</span> ID to try it out:
      <%= form_tag(gists_path) do %>
        <%= text_field_tag "id", nil, id: "id_entry" %>
      <% end %>
    </h1>
  </div>
</div>

<script>
  $('#id_entry').focus();
</script>